#!/usr/bin/env perl

use warnings;
use strict;

#use HTML::TagParser;
use Term::ANSIColor;

use vars qw/ %opt %lang $FH $filename $extension %CONFIG /;

use Data::Dumper; #Debug

my $DOGPATH = $ENV{"HOME"} . "/setup/dotfiles/dogrc";
# our %CONFIG;
require "$DOGPATH/.dogrc";

#######################################
# Command line processing
#######################################
sub init () {
    use Getopt::Std;
    my $opt_string = 'hx:';
    getopts("$opt_string", \%opt) or help();
    help() if $opt{h};
    return getNames();
}

#######################################
# Help
#######################################
sub help() {
    print STDERR << "EOF";
NAME
    dog - prints the file to standatd output with source highlighting

SYNOPSIS
    dog [OPTION] [FILE]

DESCRIPTION
    -n
    	Show line numbers
    -x LANGUAGE
    	Specify explicitly the language fi the following input files (rather than letting the compiler choose a default based on the file name suffix). Possible values for LANGUAGE are:
    <TODO: Language list>

EOF
    exit;
}

#######################################
# Get the names
#######################################
sub getNames() {
    if (! $ARGV[0]) {
	die "No file to open, $!";
    }
    my $fname = $ARGV[0];
    my ($ext) = $fname =~ /(\.[^.]+)$/;
    open my $fh, '<', $fname or die "Cannot open file $fname, $!";
    return ($fh, $fname, $ext);
}

#######################################
# Open configuration and set the language
#######################################

sub config() {

    if (!$extension && !$opt{x}) {
	# If no explicit language + no extension
	cat();
	exit;
    } else {
	# return language($conf_fh);
	# print Dumper($CONFIG{'LANGS'});
	print Dumper(\%CONFIG{'LANGS'});
    }
}

####################
# Identify language
####################
sub language () {
    #####
    # my %temp = ();
    # $temp{"LANGS"}{"PATH"} = "$DOGPATH/langs";
    # $temp{"LANGS"}{"PERL"}{"FILE"} = $temp{"LANGS"}{"PATH"} . "/perl.dog";
    # $temp{"LANGS"}{"PERL"}{"REGEX"} = qr/\.p(l|m)$/;
    # print Dumper(\%temp);
    #####
    
    # Expects filehandle
    my $fh = $_[0];
    my %config;
    
    # First get the configuration HTML (sorta):
    my @stack = ();
    #while(<$fh>) {
    #if 
    #}
    
    #Placeholder
    my %a;
    return %a; 
}

#######################################
# CAT
#######################################
sub cat() {
    #open (FILE, "<$filename") or die "Cannot open file $filename, $!";
    print colored ("#######################################\n", 'green');
    print colored ("# Cannot identify language...\n", 'green');
    print colored ("#######################################\n", 'green');
    while (<$FH>) {
	print "$_";
    }
    print colored ("#######################################\n", 'green');
}


#######################################
# Main
#######################################
($FH, $filename, $extension) = init();
%lang = config();
#print $filename . "\n";
#print $extension . "\n";
