#!/bin/bash

USAGE="\
#######################################\n\
# githubInit <username> <new repo name>\n\
#######################################"

if [[ "$#" -ne 2 ]]; then
    echo "Illegal number of arguments!"
    echo -e ${USAGE}
    exit -1
fi

curl -u "$1" https://api.github.com/user/repos -d "{\"name\":\"$2\"}"
git remote add origin git@github.com:$1/$2.git
git push --set-upstream origin master
git push

